name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn 
          yarn docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
        run:
            cd docs/.vitepress/dist  #进到dist目录
            git init  #执行这些git命令
            git add -A  
            git commit -m 'deploy'
            git push -f git@github.com:zwxyyds/vitepress-learn.git master:gh-pages  #提交到这个分支
            cd -
            rm -rf docs/.vitepress/dist  #删除dist文件夹

